server:
  port: 8081

spring:
  application:
    name: bjj-manager-api
  
  # Configuração necessária para o banco de dados
  datasource:
    url: jdbc:postgresql://localhost:5432/bjj_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Suas propriedades personalizadas
environment: local
service:
  version: 1.0.0

# Ativando métricas (Essencial para o seu artigo no Medium)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus